#!/bin/bash
# /etc/init.d/lit-password

### BEGIN INIT INFO
# Provides:          lit-password
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts leave in time password app
# Description:       This service is used to start the leave int time password app
### END INIT INFO


case "$1" in
	start)
		echo "Starting lit-password"
		/home/pi/lit-password/bin/lit-password
		;;
	stop)
		echo "Stopping lit-password"
		killall lit-password
		;;
	*)
		echo "Usage: /etc/init.d/lit-password start|stop"
		exit 1
		;;
esac

exit 0
